import generatedSiteContent from "@/lib/site-page-content.generated.json";
import {
  COMPANY_BRAND_NAME,
  COMPANY_JURISDICTION,
  COMPANY_LEGAL_NAME,
  COMPANY_PRIMARY_URL,
  COMPANY_PUBLIC_NAME,
  COMPANY_SUPPORT_EMAIL,
} from "@/lib/company";

export const SITE_LEGAL_LAST_UPDATED = generatedSiteContent.lastUpdated;

function normalizeGeneratedMarkdown(
  markdown: string,
  replacements: Array<[string, string]> = [],
) {
  let value = markdown
    .replace(/\r\n/g, "\n")
    .replaceAll("â€™", "'")
    .replaceAll("â€“", "-")
    .replaceAll("â€œ", '"')
    .replaceAll("â€\u009d", '"')
    .replaceAll("[support@policypack.org](mailto:support@policypack.org)", "support@policypack.org")
    .replace(/\n---\n/g, "\n")
    .replace(/\n---\s*/g, "\n")
    .trim();

  for (const [source, target] of replacements) {
    value = value.replaceAll(source, target);
  }

  return value.trim();
}

const privacyPolicyMarkdown = normalizeGeneratedMarkdown(
  generatedSiteContent.pages.privacyPolicy,
  [
    [
      "Manage preferences via our Cookie Policy at https://policypack.org/cookies.",
      "Manage preferences via our Cookie Policy at https://policypack.org/cookie-policy.",
    ],
    [
      "Data may be transferred globally using GDPR Article 46 safeguards (standard contractual clauses) or other lawful mechanisms. Singapore PDPA and CCPA transfer requirements are similarly observed.",
      "Data may be transferred internationally using contractual, organizational, or technical safeguards appropriate to the destination and the applicable legal framework.",
    ],
    [
      "Mail: Superlinear Technology Pte. Ltd., Attn: Legal, Singapore",
      "Business correspondence may be directed to Superlinear Technology Pte. Ltd. in Singapore.",
    ],
  ],
);

const termsAndGdprMarkdown = normalizeGeneratedMarkdown(
  generatedSiteContent.pages.termsAndGdpr,
  [
    [
      "Free tier users may generate basic legal documents subject to output watermarks and feature limits.",
      "During launch campaigns, eligible users may receive limited complimentary document access as described on the site at the time of registration.",
    ],
    [
      "Subscription refunds are discretionary except where mandated (e.g., EU 14-day cooling-off period). Request via support@policypack.org.",
      "Refund handling follows our published Refund Policy and any mandatory rights that apply under applicable law. Requests may be submitted to support@policypack.org.",
    ],
    [
      "Documents are generated by secure automated data processors trained on legal templates.",
      "Documents are generated with the help of secure automated data processors and PolicyPack's legal automation workflows.",
    ],
    [
      "Customize placeholders marked \"[YOUR COMPANY]\"",
      "Review business details, clause choices, and publication settings before using any generated document",
    ],
    [
      "# Global Privacy Appendix",
      "## 12. Global Privacy Appendix",
    ],
    [
      "**Updates**: We may revise these Terms with 30 days' notice via email or in-service alerts. Continued use constitutes acceptance.",
      "### 12.5 Updates\nWe may revise these Terms from time to time. When changes are material, we will publish the updated version on policypack.org and may also notify active users through product or billing communications.",
    ],
    [
      "**Contact**: support@policypack.org for questions or jurisdictional adaptations.",
      "### 12.6 Contact\nQuestions about these Terms or the Global Privacy Appendix may be sent to support@policypack.org.",
    ],
  ],
);

const cookiePolicyMarkdown = normalizeGeneratedMarkdown(
  generatedSiteContent.pages.cookiePolicy,
  [
    [
      "Persistent cookies retain for 1-365 days based on purpose",
      "Persistent cookies are retained only for the period reasonably necessary for the relevant purpose",
    ],
    [
      "PolicyPack reviews this policy quarterly.",
      "PolicyPack reviews this policy periodically.",
    ],
  ],
);

const refundPolicyMarkdown = normalizeGeneratedMarkdown(
  generatedSiteContent.pages.refundPolicy,
  [
    [
      "premium SaaS subscriptions",
      "premium workspace access",
    ],
  ],
);

const contactUsMarkdown = normalizeGeneratedMarkdown(
  generatedSiteContent.pages.contactUs,
);

const aboutUsMarkdown = `**Operator:** ${COMPANY_PUBLIC_NAME}  
**Jurisdiction:** ${COMPANY_JURISDICTION}  
**Website:** ${COMPANY_PRIMARY_URL}  
**Support:** ${COMPANY_SUPPORT_EMAIL}

## 1. Who We Are
1. ${COMPANY_LEGAL_NAME} is a Singapore-based technology company building practical AI systems for legal operations, compliance workflows, and document automation.
2. Through ${COMPANY_BRAND_NAME}, we help SaaS teams replace slow, fragmented legal drafting processes with faster, more structured, and more operationally useful workflows.

## 2. What PolicyPack Does
1. ${COMPANY_BRAND_NAME} helps founders and operators generate Privacy Policies, Terms of Service, Cookie Policies, Refund Policies, and supporting compliance disclosures from real product context.
2. The platform is designed for launch readiness: faster publication, clearer clauses, cleaner handoff to legal review, and ongoing maintenance as rules and platform requirements evolve.

## 3. Why Legal Automation Matters
1. Modern software businesses are expected to publish trustworthy legal pages before they can pass payment reviews, app submission checks, or customer due diligence.
2. That pressure creates a gap for lean teams: they need legal pages that are structured, current, and specific to their product, but traditional drafting can be slow, expensive, and difficult to maintain.
3. ${COMPANY_BRAND_NAME} exists to close that gap with AI-assisted legal automation that feels operational rather than overwhelming.

## 4. How We Think About AI and Compliance
1. We believe AI should reduce friction without creating false certainty. That is why ${COMPANY_BRAND_NAME} is built to produce structured drafts, surface compliance context, and keep businesses moving, while still leaving room for professional legal review where needed.
2. Our approach combines business inputs, jurisdiction signals, policy structure, and ongoing regulatory monitoring to make legal document maintenance more practical for internet businesses.

## 5. Contact
1. Product, partnership, media, and commercial inquiries may be sent to ${COMPANY_SUPPORT_EMAIL}.`;

const legalDisclaimerMarkdown = `**Operator:** ${COMPANY_PUBLIC_NAME}  
**Last Updated:** ${SITE_LEGAL_LAST_UPDATED}  
**Contact:** ${COMPANY_SUPPORT_EMAIL}

## 1. No Legal Advice
1. ${COMPANY_BRAND_NAME} is an AI-powered legal automation platform. It helps users generate and maintain compliance-oriented documents, but it does **not** provide legal advice, legal representation, or law-firm services.
2. Any policy, clause, recommendation, workflow, or draft generated through ${COMPANY_PRIMARY_URL} is provided for general informational and operational support purposes only.

## 2. No Attorney-Client Relationship
1. Using ${COMPANY_BRAND_NAME} does not create an attorney-client relationship between you and ${COMPANY_LEGAL_NAME}, ${COMPANY_BRAND_NAME}, or any person associated with the service.
2. Communications submitted through the platform should not be treated as privileged legal communications.

## 3. Professional Review May Still Be Required
1. Generated content may not address every jurisdictional nuance, regulated use case, enforcement risk, or factual scenario relevant to your business.
2. You should seek advice from a qualified licensed lawyer before relying on any generated material for high-risk, regulated, cross-border, or dispute-sensitive matters.

## 4. Customer Responsibility
1. You remain responsible for reviewing, approving, and publishing every document before commercial use.
2. You are also responsible for ensuring that the business information you provide to the platform is accurate, current, and complete.

## 5. No Guarantee of Regulatory Sufficiency
1. While ${COMPANY_BRAND_NAME} is designed to support compliance readiness, we do not guarantee that any generated output will satisfy every legal requirement applicable to your business.
2. Laws change, enforcement priorities evolve, and platform review standards differ across industries and jurisdictions.

## 6. Contact
1. Questions about this disclaimer may be sent to ${COMPANY_SUPPORT_EMAIL}.`;

export function getPrivacyPolicyMarkdown() {
  return privacyPolicyMarkdown;
}

export function getTermsAndGdprMarkdown() {
  return termsAndGdprMarkdown;
}

export function getCookiePolicyMarkdown() {
  return cookiePolicyMarkdown;
}

export function getRefundPolicyMarkdown() {
  return refundPolicyMarkdown;
}

export function getAboutUsMarkdown() {
  return aboutUsMarkdown;
}

export function getContactUsMarkdown() {
  return contactUsMarkdown;
}

export function getLegalDisclaimerMarkdown() {
  return legalDisclaimerMarkdown;
}
